[tool.poetry]
name = "qrfastapi"
version = "0.0.1"
description = "FastAPI Beer API for fun and adventure"
authors = ["Evan Baird <mrcartoonster@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
qrcode = {extras = ["pil"], version = "^6.1"}
fastapi = {extras = ["all"], version = "^0.61.1"}
psycopg2-binary = "^2.8.6"
tortoise-orm = "^0.16.17"
pytest = "^6.1.1"
pytest-emoji = "^0.2.0"
pytest-clarity = "^0.3.0-alpha.0"
pytest-picked = "^0.4.4"
pytest-cov = "^2.10.1"
pytest-html = "^2.1.1"
prettyprinter = "^0.18.0"
asyncpg = "^0.21.0"

[tool.poetry.dev-dependencies]
pre-commit = "^2.7.1"
csvkit = "^1.0.5"
yakutils = "^1.7.0"
prettyprinter = "^0.18.0"
pretty-errors = "^1.2.18"
ipython = "^7.18.1"
pyperclip = "^1.8.1"

[tool.pytest.ini_options]
addopts = "-rssxX -l --tb=short --strict --emoji -vv --diff-type=split"
xfail_strict = "True"
markers = [
  "smoke",
  "fire",
  "verify"
]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
