# -*- coding: utf-8 -*-
"""
first.

Revision ID: 208f5c54ce40
Revises:
Create Date: 2020-11-19 12:25:58.201943

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "208f5c54ce40"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("breweries")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "breweries",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "brewery_type",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("street", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("city", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("state", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "postal_code",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "website_url",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("phone", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "country",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "longitude",
            sa.NUMERIC(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "latitude",
            sa.NUMERIC(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("tags", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
